CREATE TABLE pet_family_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    related_pet_id BIGINT NOT NULL,
    relation_type VARCHAR(20) NOT NULL,
    is_biological BOOLEAN NOT NULL DEFAULT TRUE,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_pet_family_relations_pet
        FOREIGN KEY (pet_id)
        REFERENCES pets(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pet_family_relations_related_pet
        FOREIGN KEY (related_pet_id)
        REFERENCES pets(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_pet_family_relations_type
        CHECK (relation_type IN ('PARENT', 'CHILD', 'SIBLING', 'MATE')),

    CONSTRAINT chk_pet_family_relations_not_self
        CHECK (pet_id <> related_pet_id),

    CONSTRAINT uq_pet_family_relations_unique
        UNIQUE (pet_id, related_pet_id, relation_type)
);

CREATE INDEX idx_pet_family_relations_pet_id
    ON pet_family_relations (pet_id);

CREATE INDEX idx_pet_family_relations_related_pet_id
    ON pet_family_relations (related_pet_id);
