CREATE TABLE oral_health_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    submission_id UUID,
    periodontal_stage VARCHAR(20) NOT NULL,
    tartar_level VARCHAR(20),
    gingiva_inflammation BOOLEAN,
    halitosis BOOLEAN,
    tooth_loss_count INT NOT NULL DEFAULT 0,
    note TEXT,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_oral_health_records_pet
        FOREIGN KEY (pet_id)
        REFERENCES pets(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_oral_health_records_submission
        FOREIGN KEY (submission_id)
        REFERENCES submissions(id)
        ON DELETE SET NULL,

    CONSTRAINT chk_oral_health_records_periodontal_stage
        CHECK (periodontal_stage IN ('NONE', 'GINGIVITIS', 'STAGE1', 'STAGE2', 'STAGE3', 'STAGE4')),

    CONSTRAINT chk_oral_health_records_tartar_level
        CHECK (tartar_level IS NULL OR tartar_level IN ('NONE', 'LOW', 'MEDIUM', 'HIGH')),

    CONSTRAINT chk_oral_health_records_tooth_loss_count
        CHECK (tooth_loss_count >= 0)
);

CREATE INDEX idx_oral_health_records_pet_id
    ON oral_health_records (pet_id);

CREATE INDEX idx_oral_health_records_submission_id
    ON oral_health_records (submission_id);

INSERT INTO conditions (name, species, description) VALUES
    ('Periodontitis', 'DOG', 'A progressive inflammatory disease affecting the tissues that support a dog''s teeth.'),
    ('Periodontitis', 'CAT', 'A progressive inflammatory disease affecting the tissues that support a cat''s teeth.')
ON CONFLICT (name, species) DO NOTHING;

INSERT INTO check_methods (name, description)
VALUES ('Oral Examination', 'A visual and clinical inspection used to assess the pet''s oral health status.')
ON CONFLICT (name) DO NOTHING;

INSERT INTO condition_check_methods (condition_id, check_method_id)
SELECT c.id, cm.id
FROM conditions c
JOIN check_methods cm ON cm.name = 'Oral Examination'
WHERE c.name = 'Periodontitis'
ON CONFLICT (condition_id, check_method_id) DO NOTHING;

INSERT INTO condition_translations (condition_id, language_id, translated_name, translated_description)
SELECT
    c.id,
    l.id,
    CASE
        WHEN l.code = 'ko' THEN '치주염'
        WHEN l.code = 'en' THEN 'Periodontitis'
    END,
    CASE
        WHEN l.code = 'ko' THEN '반려동물의 치아를 지지하는 잇몸과 주변 조직에 염증이 진행되는 구강 질환입니다.'
        WHEN l.code = 'en' THEN 'A progressive inflammatory disease affecting the tissues that support the teeth.'
    END
FROM conditions c
JOIN languages l ON l.code IN ('ko', 'en')
WHERE c.name = 'Periodontitis'
ON CONFLICT (condition_id, language_id) DO UPDATE
SET
    translated_name = EXCLUDED.translated_name,
    translated_description = EXCLUDED.translated_description;

INSERT INTO check_method_translations (check_method_id, language_id, translated_name, translated_description)
SELECT
    cm.id,
    l.id,
    CASE
        WHEN l.code = 'ko' THEN '구강 검사'
        WHEN l.code = 'en' THEN 'Oral Examination'
    END,
    CASE
        WHEN l.code = 'ko' THEN '반려동물의 치아, 잇몸, 구강 상태를 시진과 촉진으로 확인하는 검사 방법입니다.'
        WHEN l.code = 'en' THEN 'A visual and clinical examination used to assess teeth, gums, and overall oral condition.'
    END
FROM check_methods cm
JOIN languages l ON l.code IN ('ko', 'en')
WHERE cm.name = 'Oral Examination'
ON CONFLICT (check_method_id, language_id) DO UPDATE
SET
    translated_name = EXCLUDED.translated_name,
    translated_description = EXCLUDED.translated_description;
