spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD:}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    placeholders:
      ai:
        user:
          email: ${AI_MODEL_SERVICE_EMAIL:ai-service@local.test}
          password-hash: ${AI_MODEL_SERVICE_PASSWORD_HASH:test}

  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: ${SMTP_PORT}
          auth: true
          starttls:
            enable: false
            required: false

  quartz:
    auto-startup: false
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 10000
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.instanceName: ClusteredQuartzScheduler
      org.quartz.threadPool.threadCount: 1

  security:
    oauth2:
      client:
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me

server:
  port: 8088

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration:
      minutes: 1440
  refresh-token:
    expiration:
      days: 7
    max-count: 10

app:
  mail:
    from: ${SMTP_FROM}
    allowed-emails: ${ALLOWED_EMAILS_COMMA_SEPARATED:}
  token:
    email-verification:
      secret: ${EMAIL_VERIFICATION_SECRET}
      tries:
        count: 10000
        duration:
          days: 1
      failure:
        attempts: 100
      lock:
        duration:
          minutes: 30
      expiration:
        minutes: 15
    password-reset:
      expiration:
        minutes: 15

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_BUCKET}
    cloudfront:
      domain: ${AWS_CLOUDFRONT_DOMAIN:}

local-storage:
  url-prefix: ${LOCAL_STORAGE_URL_PREFIX}
  ai-url-prefix: ${AI_MODEL_SERVICE_URL_PREFIX}
  local-resource-path: ${LOCAL_RESOURCE_PATH}

inference-service:
  retry:
    max-attempts: ${INFERENCE_SERVICE_RETRY_MAX_ATTEMPTS}
  timeout:
    seconds: ${INFERENCE_SERVICE_TIMEOUT_SECONDS}
  batch:
    size: ${INFERENCE_SERVICE_BATCH_SIZE}
  interval:
    seconds: ${INFERENCE_SERVICE_INTERVAL_SECONDS}